version: 2

jobs:

  build-linux:
    machine:
        enabled: true
    steps:
      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
            echo ". $HOME/.nix-profile/etc/profile.d/nix.sh" >> $BASH_ENV
            sudo mkdir -p /etc/nix
            # Enable sandbox
            echo "sandbox = true" | sudo tee -a /etc/nix/nix.conf
            # Keep derivations and their outputs for better caching
            echo "keep-outputs = true" | sudo tee -a /etc/nix/nix.conf
            echo "keep-derivations = true" | sudo tee -a /etc/nix/nix.conf
      - checkout
      - run: nix-build release.nix --arg systems '[builtins.currentSystem]' -A tests --max-jobs 2

workflows:
  version: 2
  build:
    jobs:
      - build-linux
